name: ci-main

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:

  hello:
    name: hello-world
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Print greeting
        run: echo "Olá!"

      - name: Print additional messages
        run: |
          echo "Foi mensagem é exibida como segundo passo do seu Job Inicial."
          echo "Meus parabéns!"

  python-check:
    name: python-runtime-check
    runs-on: ubuntu-22.04
    needs: hello
    timeout-minutes: 5

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Python script
        run: |
          python - <<EOF
          variavel = "Hello World !!!"
          print(variavel)
          EOF

  node-check:
    name: node-runtime-check
    runs-on: ubuntu-22.04
    needs: hello
    timeout-minutes: 5

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.13.1"

      - name: Verify Node version
        run: node --version
